import React from 'react'
import "../css/base.css";
import "../css/element.css";
import "../css/media.css";
import "../css/header.css";
import "../css/main.css";
import '../css/footer.css';

function Aboutus() {
    return (
        <>
            <main id="main" className="site-primary">
                <div className="site-content">
                    <div className="homepage-content">
                        <div data-elementor-type="wp-page" data-elementor-id="1544" className="elementor elementor-1544" data-elementor-settings="[]">
                            <div className="elementor-section-wrap">
                                <section className="elementor-section elementor-top-section elementor-element elementor-element-99fa573 elementor-section-full_width elementor-section-height-default elementor-section-height-default" data-id="99fa573" data-element_type="section">
                                    <div className="elementor-container elementor-column-gap-no">
                                        <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-305ee4c" data-id="305ee4c" data-element_type="column">
                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                <div className="elementor-element elementor-element-9906406 elementor-widget elementor-widget-bacola-hero-banner" data-id="9906406" data-element_type="widget" data-widget_type="bacola-hero-banner.default">
                                                    <div className="elementor-widget-container">
                                                        <div className="page-hero"><div className="container"><h1 className="entry-title">About for Bacola</h1><h4 className="entry-subtitle">We can do more for you</h4></div><div className="hero-image"><img src="https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-header.jpg" alt="hero-banner"/></div></div></div></div></div></div></div></section>
                                <section className="elementor-section elementor-top-section elementor-element elementor-element-be51b6a elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="be51b6a" data-element_type="section">
                                    <div className="elementor-container elementor-column-gap-extended">
                                        <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-5a15344" data-id="5a15344" data-element_type="column">
                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                <div className="elementor-element elementor-element-c7bd744 elementor-widget elementor-widget-heading" data-id="c7bd744" data-element_type="widget" data-widget_type="heading.default">
                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">In nec purus eget neque accumsan finibus. Duis condimentum elit ut libero commodo iaculis. Donec augue diam, tristique et ultricies nec, consectetur quis enim. Nullam id rutrum ex. Aliquam a lectus id lacus rhoncus dapibus non ac justo. Vivamus lacinia vestibulum metus in dapibus. Vestibulum sit amet sollicitudin enim. Ut id interdum turpis. Curabitur porta auctor quam, pretium facilisis nisl. Pellentesque efficitur elit ante, vel vulputate tortor blandit nec.</p></div></div></div></div></div></section>
                                <section className="elementor-section elementor-top-section elementor-element elementor-element-3551755 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="3551755" data-element_type="section">
                                    <div className="elementor-container elementor-column-gap-extended">
                                        <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-6f96f87" data-id="6f96f87" data-element_type="column">
                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                <section className="elementor-section elementor-inner-section elementor-element elementor-element-d2a69d1 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="d2a69d1" data-element_type="section">
                                                    <div className="elementor-container elementor-column-gap-no">
                                                        <div className="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-3da8ad0" data-id="3da8ad0" data-element_type="column">
                                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                                <div className="elementor-element elementor-element-bf5a32e elementor-widget elementor-widget-heading" data-id="bf5a32e" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <h2 className="elementor-heading-title elementor-size-default">Quisque erat urna, congue et libero in <br/> eleifend euismod velit.</h2></div></div></div></div></div></section>
                                                <section className="elementor-section elementor-inner-section elementor-element elementor-element-dae2cc1 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="dae2cc1" data-element_type="section">
                                                    <div className="elementor-container elementor-column-gap-no">
                                                        <div className="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-769fd1d" data-id="769fd1d" data-element_type="column">
                                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                                <div className="elementor-element elementor-element-563075f elementor-widget elementor-widget-heading" data-id="563075f" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">In nec purus eget neque accumsan finibus. Duis condimentum elit ut libero commodo iaculis. Donec augue diam, tristique et ultricies nec, consectetur quis enim. Nullam id rutrum ex. Aliquam a lectus id lacus rhoncus dapibus non ac justo. Vivamus lacinia vestibulum metus in dapibus. Vestibulum sit amet sollicitudin enim. Ut id interdum turpis. Curabitur porta auctor quam, pretium facilisis nisl. Pellentesque efficitur elit ante, vel vulputate tortor blandit nec.</p></div></div></div></div></div></section></div></div></div></section>
                                <section className="elementor-section elementor-top-section elementor-element elementor-element-f600bf8 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="f600bf8" data-element_type="section">
                                    <div className="elementor-container elementor-column-gap-no">
                                        <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-e769e7d" data-id="e769e7d" data-element_type="column">
                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                <section className="elementor-section elementor-inner-section elementor-element elementor-element-faa9e1d elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="faa9e1d" data-element_type="section">
                                                    <div className="elementor-container elementor-column-gap-extended">
                                                        <div className="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-915cf91" data-id="915cf91" data-element_type="column">
                                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                                <div className="elementor-element elementor-element-393e4f6 elementor-widget elementor-widget-image" data-id="393e4f6" data-element_type="widget" data-widget_type="image.default">
                                                                    <div className="elementor-widget-container"> <img width="600" height="900" src="https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-people.jpg" className="attachment-large size-large" alt="" loading="lazy" srcset="https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-people.jpg 600w, https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-people-200x300.jpg 200w, https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-people-36x54.jpg 36w, https://klbtheme.com/bacola/wp-content/uploads/2021/08/about-people-64x96.jpg 64w" sizes="(max-width: 600px) 100vw, 600px" /></div></div></div></div><div className="elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-1fe836e" data-id="1fe836e" data-element_type="column">
                                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                                <div className="elementor-element elementor-element-13850b5 elementor-widget elementor-widget-heading" data-id="13850b5" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <span className="elementor-heading-title elementor-size-default">Rachel Leonard - Bacola CEO</span></div></div><div className="elementor-element elementor-element-9ecc34f elementor-widget elementor-widget-heading" data-id="9ecc34f" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <h3 className="elementor-heading-title elementor-size-default">Duis convallis luctus pretium. Pellentesque habitant morbi</h3></div></div><div className="elementor-element elementor-element-5aa4d5a elementor-widget elementor-widget-heading" data-id="5aa4d5a" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p></div></div><div className="elementor-element elementor-element-037413a elementor-widget elementor-widget-heading" data-id="037413a" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">In fermentum mi ut sapien semper, a sagittis lorem vulputate. Integer gravida, dui eget aliquet tempus, turpis orci vehicula ipsum, eget porttitor sapien tortor at neque. Cras id pulvinar lacus, ac volutpat neque. Ut at magna id justo bibendum lobortis. Integer tortor nulla, ultricies et nisi sit amet, interdum dictum felis. In semper laoreet dui vitae pharetra. Etiam sit amet molestie nulla, eu efficitur orci. Praesent rutrum ante justo, eget malesuada ante ornare ac. Ut dignissim blandit urna, eget euismod leo rhoncus nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque lobortis libero ante. Nullam in feugiat erat. Aenean sed justo dapibus, sodales nisi ut, fringilla lorem. Vestibulum in orci ac nisl condimentum fermentum at et sem. Curabitur fermentum dolor eu lacus consectetur varius.</p></div></div></div></div></div></section>
                                                <section className="elementor-section elementor-inner-section elementor-element elementor-element-ae4c3f3 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="ae4c3f3" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                                                    <div className="elementor-container elementor-column-gap-extended">
                                                        <div className="elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-c55e507" data-id="c55e507" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                                <div className="elementor-element elementor-element-56f89a9 elementor-widget elementor-widget-heading" data-id="56f89a9" data-element_type="widget" data-widget_type="heading.default">
                                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">In nec purus eget neque accumsan finibus. Duis condimentum elit ut libero commodo iaculis. Donec augue diam, tristique et ultricies nec, consectetur quis enim. Nullam id rutrum ex. Aliquam a lectus id lacus rhoncus dapibus non ac justo. Vivamus lacinia vestibulum metus in dapibus. Vestibulum sit amet sollicitudin enim. Ut id interdum turpis. Curabitur porta auctor quam, pretium facilisis nisl. Pellentesque efficitur elit ante, vel vulputate tortor blandit nec. </p></div></div></div></div></div></section></div></div></div></section>
                                <section className="elementor-section elementor-top-section elementor-element elementor-element-c3a3091 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="c3a3091" data-element_type="section">
                                    <div className="elementor-container elementor-column-gap-extended">
                                        <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7ae1ceb" data-id="7ae1ceb" data-element_type="column">
                                            <div className="elementor-widget-wrap elementor-element-populated">
                                                <div className="elementor-element elementor-element-0ab0b16 elementor-widget elementor-widget-heading" data-id="0ab0b16" data-element_type="widget" data-widget_type="heading.default">
                                                    <div className="elementor-widget-container"> <p className="elementor-heading-title elementor-size-default">In nec purus eget neque accumsan finibus. Duis condimentum elit ut libero commodo iaculis. Donec augue diam, tristique et ultricies nec, consectetur quis enim. Nullam id rutrum ex. Aliquam a lectus id lacus rhoncus dapibus non ac justo. Vivamus lacinia vestibulum metus in dapibus. Vestibulum sit amet sollicitudin enim. Ut id interdum turpis. Curabitur porta auctor quam, pretium facilisis nisl. Pellentesque efficitur elit ante, vel vulputate tortor blandit nec. </p></div></div></div></div></div></section></div></div></div></div></main>
            </>
            )
}

            export default Aboutus;